project:
  type: website

website:
  title: "David Day | 戴惟"
  site-url: 'https://davidday.tw'
  google-analytics: "G-GZ6NKY8J14"

  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/daviddaytw

format:
  html:
    theme: minty
    css: styles.css
    toc: true

margin-header: google-translate.html
