project:
  type: website

website:
  title: "David Day | 戴惟"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/daviddaytw
format:
  html:
    theme: minty
    css: styles.css
    toc: true

margin-header: google-translate.html

