name: Publish Website

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Upload to server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.davidday.tw
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
